from typing import Any

def get_chromedriver_filename(): ...
def get_variable_separator(): ...
def get_chromedriver_url(version): ...
def find_binary_in_path(filename): ...
def get_latest_release_for_version(version: Any | None = ...): ...
def get_chrome_major_version(): ...
def check_version(binary, required_version): ...
def get_chromedriver_path(): ...
def print_chromedriver_path() -> None: ...
