version: 2
updates:
  # Check for updates to the used NPM packages every week
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    commit-message:
      prefix: "chore"
      include: "scope"
    assignees:
      - eikowagenknecht
    groups:
      # Everything that is not a major update
      npm-updates:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Check for updates to GitHub Actions every week
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    commit-message:
      prefix: "ci"
      include: "scope"
    assignees:
      - eikowagenknecht

  # Check for updates to Docker images every week
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    commit-message:
      prefix: "build"
      include: "scope"
    assignees:
      - eikowagenknecht
