version: 2
updates:
  # Check for updates to the used Python packages every weekday
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    versioning-strategy: increase
    commit-message:
      prefix: "chore"
      include: "scope"

  # Check for updates to GitHub Actions every weekday
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Check for updates to Docker images every weekday
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    commit-message:
      prefix: "build"
      include: "scope"
