[tool.isort]

profile = "black"

[tool.mypy]

python_version = "3.10"
warn_unused_configs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_any_unimported = true
disallow_any_expr = true
disallow_any_generics = true

[tool.pylint.master]

# https://stackoverflow.com/questions/1899436/pylint-unable-to-import-error-how-to-set-pythonpath
# Doesn't work with pyproject.toml but also doesn't seem to bee needed anymore with it
#init-hook = "from pylint.config import find_pylintrc; import os, sys; sys.path.append(os.path.dirname(find_pylintrc()))"

[tool.pylint.messages_control]

# Some disabled because they are too verbose, some because they are handled better by flake8
disable = [
    "raw-checker-failed",
    "bad-inline-option",
    "locally-disabled",
    "file-ignored",
    "suppressed-message",
    "useless-suppression",
    "deprecated-pragma",
    "use-symbolic-message-instead",
    "missing-module-docstring",
    "missing-function-docstring",
    "missing-class-docstring",
    "line-too-long",
    "fixme",
    "import-error",
    "unused-import",
    "invalid-name",
]