[tool.poetry]
name = "lootscraper"
version = "1.4.0"
description = "RSS feeds and Telegram bot for free game and loot offers."
authors = ["Eiko Wagenknecht <git@eiko-wagenknecht.de>"]
readme = "README.md"
license = "CC-BY-NC-SA-4.0"
repository = "https://github.com/eikowagenknecht/lootscraper"
include = ["config.default.toml"]

[tool.poetry.scripts]
lootscraper = 'lootscraper.main:main'

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/eikowagenknecht/lootscraper/issues"

[tool.poetry.dependencies]
python = "^3.11"
alembic = "^1.10.4"
feedgen = "^0.9.0"
humanize = "^4.6.0"
httpx = "^0.23.3"
python-telegram-bot = { version = "^20.2", extras = ["rate-limiter"] }
playwright = "^1.32.1"
SQLAlchemy = "^2.0.11"
Unidecode = "^1.3.6"
xvfbwrapper = "^0.2.9"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
# Linting
ruff = "^0.0.263"
# Formatting
black = "^23.3.0"
# Type checking
mypy = "^1.2"
# Profiling
# scalene = "^1.5.19"
pytest = "^7.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
# See rules here: https://beta.ruff.rs/docs/rules/
select = [
    "F",
    "W",
    "B", 
    "E", 
    "I", 
    "N", 
    "PLC",
    "PLE",
    # "PLR",
    "PLW",
    "TRY",
    "PTH",
    "TID",
    "SIM",
    "ARG",
    "TCH",
    "RET",
    "UP",
    "YTT",
    "SLF",
    "ANN",
    "S",
    "A",
    "COM",
    "DTZ",
    "C4",
    "ISC",
    "PIE",
    "T20",
    "PYI",
    "PT",
    "Q",
    "RSE",
    "INP",
    "ICN"
]

ignore = [
    "S101", # Use of assert detected
    "E501", # Line too long
    "ANN101", # Missing type annotation for self in method
    "PLR2004", # Magic value in comparison
    "INP001", # Implicit namespace package
    "TRY003", # Long messages in exceptions
] 

[tool.mypy]
python_version = "3.11"
# ignore imports from 3rd party libraries where no stubs are available
ignore_missing_imports = true
warn_unused_configs = true
disallow_untyped_calls = true
disallow_untyped_defs = true
# disallow_any_unimported = true
# disallow_any_expr = true
disallow_any_generics = true
# plugins = "sqlalchemy.ext.mypy.plugin" # Needed for SQLAlchemy 1.4 only