blank_issues_enabled: false
contact_links:
  - name: 🚀 Feature Request
    url: https://github.com/eikowagenknecht/lootscraper/discussions/new?category=feature-request
    about: Remember to search for existing feature requests and "up-vote" those that you like.