from typing import Any

DESCRIPTOR: Any
AgeRatingCategoryEnum: Any
AgeRatingRatingEnum: Any
GenderGenderEnum: Any
CharacterSpeciesEnum: Any
DateFormatChangeDateCategoryEnum: Any
WebsiteCategoryEnum: Any
ExternalGameCategoryEnum: Any
ExternalGameMediaEnum: Any
GameCategoryEnum: Any
GameStatusEnum: Any
GameVersionFeatureCategoryEnum: Any
GameVersionFeatureValueIncludedFeatureEnum: Any
PlatformCategoryEnum: Any
RegionRegionEnum: Any
TestDummyEnumTestEnum: Any
AGERATING_CATEGORY_NULL: int
ESRB: int
PEGI: int
CERO: int
USK: int
GRAC: int
CLASS_IND: int
ACB: int
AGERATING_RATING_NULL: int
THREE: int
SEVEN: int
TWELVE: int
SIXTEEN: int
EIGHTEEN: int
RP: int
EC: int
E: int
E10: int
T: int
M: int
AO: int
CERO_A: int
CERO_B: int
CERO_C: int
CERO_D: int
CERO_Z: int
USK_0: int
USK_6: int
USK_12: int
USK_18: int
GRAC_ALL: int
GRAC_TWELVE: int
GRAC_FIFTEEN: int
GRAC_EIGHTEEN: int
GRAC_TESTING: int
CLASS_IND_L: int
CLASS_IND_TEN: int
CLASS_IND_TWELVE: int
CLASS_IND_FOURTEEN: int
CLASS_IND_SIXTEEN: int
CLASS_IND_EIGHTEEN: int
ACB_G: int
ACB_PG: int
ACB_M: int
ACB_MA15: int
ACB_R18: int
ACB_RC: int
MALE: int
FEMALE: int
OTHER: int
CHARACTER_SPECIES_NULL: int
HUMAN: int
ALIEN: int
ANIMAL: int
ANDROID: int
UNKNOWN: int
YYYYMMMMDD: int
YYYYMMMM: int
YYYY: int
YYYYQ1: int
YYYYQ2: int
YYYYQ3: int
YYYYQ4: int
TBD: int
WEBSITE_CATEGORY_NULL: int
WEBSITE_OFFICIAL: int
WEBSITE_WIKIA: int
WEBSITE_WIKIPEDIA: int
WEBSITE_FACEBOOK: int
WEBSITE_TWITTER: int
WEBSITE_TWITCH: int
WEBSITE_INSTAGRAM: int
WEBSITE_YOUTUBE: int
WEBSITE_IPHONE: int
WEBSITE_IPAD: int
WEBSITE_ANDROID: int
WEBSITE_STEAM: int
WEBSITE_REDDIT: int
WEBSITE_ITCH: int
WEBSITE_EPICGAMES: int
WEBSITE_GOG: int
WEBSITE_DISCORD: int
EXTERNALGAME_CATEGORY_NULL: int
EXTERNALGAME_STEAM: int
EXTERNALGAME_GOG: int
EXTERNALGAME_YOUTUBE: int
EXTERNALGAME_MICROSOFT: int
EXTERNALGAME_APPLE: int
EXTERNALGAME_TWITCH: int
EXTERNALGAME_ANDROID: int
EXTERNALGAME_AMAZON_ASIN: int
EXTERNALGAME_AMAZON_LUNA: int
EXTERNALGAME_AMAZON_ADG: int
EXTERNALGAME_EPIC_GAME_STORE: int
EXTERNALGAME_OCULUS: int
EXTERNALGAME_MEDIA_NULL: int
EXTERNALGAME_DIGITAL: int
EXTERNALGAME_PHYSICAL: int
MAIN_GAME: int
DLC_ADDON: int
EXPANSION: int
BUNDLE: int
STANDALONE_EXPANSION: int
MOD: int
EPISODE: int
SEASON: int
REMAKE: int
REMASTER: int
EXPANDED_GAME: int
PORT: int
FORK: int
RELEASED: int
ALPHA: int
BETA: int
EARLY_ACCESS: int
OFFLINE: int
CANCELLED: int
RUMORED: int
DELISTED: int
BOOLEAN: int
DESCRIPTION: int
NOT_INCLUDED: int
INCLUDED: int
PRE_ORDER_ONLY: int
PLATFORM_CATEGORY_NULL: int
CONSOLE: int
ARCADE: int
PLATFORM: int
OPERATING_SYSTEM: int
PORTABLE_CONSOLE: int
COMPUTER: int
REGION_REGION_NULL: int
EUROPE: int
NORTH_AMERICA: int
AUSTRALIA: int
NEW_ZEALAND: int
JAPAN: int
CHINA: int
ASIA: int
WORLDWIDE: int
KOREA: int
BRAZIL: int
TESTDUMMY_ENUM_TEST_NULL: int
ENUM1: int
ENUM2: int
Count: Any
MultiQueryResult: Any
MultiQueryResultArray: Any
AgeRatingResult: Any
AgeRating: Any
AgeRatingContentDescriptionResult: Any
AgeRatingContentDescription: Any
AlternativeNameResult: Any
AlternativeName: Any
ArtworkResult: Any
Artwork: Any
CharacterResult: Any
Character: Any
CharacterMugShotResult: Any
CharacterMugShot: Any
CollectionResult: Any
Collection: Any
CompanyResult: Any
Company: Any
CompanyLogoResult: Any
CompanyLogo: Any
CompanyWebsiteResult: Any
CompanyWebsite: Any
CoverResult: Any
Cover: Any
ExternalGameResult: Any
ExternalGame: Any
FranchiseResult: Any
Franchise: Any
GameResult: Any
Game: Any
GameEngineResult: Any
GameEngine: Any
GameEngineLogoResult: Any
GameEngineLogo: Any
GameModeResult: Any
GameMode: Any
GameVersionResult: Any
GameVersion: Any
GameVersionFeatureResult: Any
GameVersionFeature: Any
GameVersionFeatureValueResult: Any
GameVersionFeatureValue: Any
GameVideoResult: Any
GameVideo: Any
GenreResult: Any
Genre: Any
InvolvedCompanyResult: Any
InvolvedCompany: Any
KeywordResult: Any
Keyword: Any
MultiplayerModeResult: Any
MultiplayerMode: Any
PlatformResult: Any
Platform: Any
PlatformFamilyResult: Any
PlatformFamily: Any
PlatformLogoResult: Any
PlatformLogo: Any
PlatformVersionResult: Any
PlatformVersion: Any
PlatformVersionCompanyResult: Any
PlatformVersionCompany: Any
PlatformVersionReleaseDateResult: Any
PlatformVersionReleaseDate: Any
PlatformWebsiteResult: Any
PlatformWebsite: Any
PlayerPerspectiveResult: Any
PlayerPerspective: Any
ReleaseDateResult: Any
ReleaseDate: Any
ScreenshotResult: Any
Screenshot: Any
SearchResult: Any
Search: Any
TestDummyResult: Any
TestDummy: Any
ThemeResult: Any
Theme: Any
WebsiteResult: Any
Website: Any
