name: Publish to Docker Hub CI

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3.6.2
      with:
        images: eikowagenknecht/lootscraper
        flavor: |
          # tagges semver releases get a "latest" entry as well
          latest=auto
          prefix=
          suffix=
        tags: |
          # refs/branches/main -> "main"
          type=ref,event=branch
          # refs/tags/v1.2.3 -> "1.2.3"
          type=semver,pattern={{version}}
          # refs/tags/v1.2.3 -> "1.2"
          type=semver,pattern={{major}}.{{minor}}
          # refs/tags/v1.2.3 -> "1", only if >0
          type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}

    - name: Log in to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1.14.1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2.9.0
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
