name: Publish to Docker Hub CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
    - name: Build the Docker image
      run: docker build . --tag eikowagenknecht/lootscraper:$(date +%s) --tag eikowagenknecht/lootscraper:latest
