name: Publish to Github Packages

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v3.6.2
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        # tagged semver releases get a (latest) entry as well
        flavor: |
          latest=auto
          prefix=
          suffix=
        # refs/branches/main -> (main)
        # refs/tags/v1.2.3 -> (1.2.3)
        # refs/tags/v1.2.3 -> (1.2)
        # refs/tags/v1.2.3 -> (1), only if greater zero
        tags: |
          type=ref,event=branch
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}

    - name: Log in to Github Packages
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1.14.1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2.9.0
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
