# Lint with ruff
# Check format with ruff
# Check types with mypy

name: quality-check

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

permissions:
  contents: read # for checkout

jobs:
  quality-check:
    # Do not run for automated release commits (otherwise we would run into a deadlock situation)
    if: ${{ !contains(github.event.head_commit.message, 'chore(release):') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv pip install ".[dev]"

      - name: Lint with ruff
        run: uv run ruff check .

      - name: Check format with ruff
        run: uv run ruff format . --check

      - name: Check types with mypy
        run: uv run mypy .
