# Lint and test the codebase

name: quality-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  quality-check:
    # Do not run for automated release commits (otherwise we would run into a deadlock situation)
    if: ${{ !contains(github.event.head_commit.message, 'chore(release):') }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm run type-check

      - name: Lint
        run: pnpm run lint

      - name: Test
        run: pnpm run test

      - name: Build
        run: pnpm run build
