# Lint with ruff
# Check format with ruff
# Check types with mypy

name: quality-check

on:
  push:
    branches:
      - main
      - next
  pull_request:
    branches:
      - main
      - next

permissions:
  contents: read # for checkout

jobs:
  quality-check:
    # Do not run for automated release commits (otherwise we would run into a deadlock situation)
    if: ${{ !contains(github.event.head_commit.message, 'chore(release):') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Create and activate virtual environment
        run: |
          uv venv
          echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: uv sync

      - name: Lint with ruff
        run: ruff check .

      - name: Check format with ruff
        run: ruff format . --check

      - name: Check types with mypy
        run: mypy .
