name: semantic-release

on:
  # Run after the quality check workflow on main and next
  # workflow_run:
  #   workflows:
  #     - "quality-check"
  #   branches:
  #     - main
  #     - next
  #   types:
  #     - completed
  # Also allow manual triggering
  workflow_dispatch:

permissions:
  contents: read # for checkout

jobs:
  release:
    # Only run if manually triggered or the quality check workflow succeeded
    if: github.event_name == 'workflow_dispatch'
    # || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    concurrency:
      group: release-${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    permissions:
      id-token: write
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Semantic Release
        uses: python-semantic-release/python-semantic-release@v8.3.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog: "false"

        #   git_committer_name: eikowagenknecht
        #   git_committer_email: git@eiko-wagenknecht.de

      # - name: Install python-semantic-release
      #   run: |
      #     pip install python-semantic-release

      # # Does not work, the token is not used
      # - name: Semantic release
      #   env:
      #     GH_TOKEN: ${{ secrets.GH_SEMREL }}
      #   run: |
      #     semantic-release version
